"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Plus } from "lucide-react";
import { ScreenHeader } from "@/components/screen-header";
import { PatternArt, CraftArt } from "@/components/craft-art";
type Draft={name:string;yarn:string;notes:string;patternId:string};
export default function ProjectsPage(){const [draft,setDraft]=useState<Draft|null>(null);useEffect(()=>{const timer=window.setTimeout(()=>{const value=localStorage.getItem("stitchly:last-project");if(value){try{setDraft(JSON.parse(value))}catch{}}},0);return()=>clearTimeout(timer)},[]);return <div className="pb-10"><ScreenHeader title="Your projects" right={<Link href="/library" className="flex size-10 items-center justify-center rounded-2xl bg-primary text-white"><Plus className="size-5"/></Link>}/><div className="px-5 pt-7 md:px-8">{draft?<><p className="text-xs font-extrabold uppercase tracking-[.15em] text-primary">Making now</p><div className="mt-3 grid md:grid-cols-2"><Link href="/projects/aran-scarf-mum/reader" className="stitch-card group overflow-hidden"><div className="relative h-44 bg-[#dff4fb]"><PatternArt index={0} className="absolute bottom-[-2rem] right-5 size-52"/></div><div className="p-5"><h2 className="font-heading text-xl font-black">{draft.name}</h2><p className="mt-1 text-sm text-muted-foreground">{draft.yarn||"Materials not added yet"}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-extrabold text-primary">Open reader <ArrowRight className="size-4"/></span></div></Link></div></>:<EmptyProjects/>}<Link href="/projects/aran-scarf-mum/reader" className="mt-8 flex items-center justify-between rounded-2xl border border-dashed bg-white p-4"><div><p className="font-heading text-sm font-extrabold">Preview an example reader</p><p className="text-xs text-muted-foreground">Explore without creating a project</p></div><ArrowRight className="size-4 text-primary"/></Link></div></div>}
function EmptyProjects(){return <div className="py-8 text-center"><div className="relative mx-auto flex size-64 items-center justify-center rounded-full bg-[#ffe6a8]"><CraftArt art="yarn" className="size-48"/></div><h1 className="font-heading mt-5 text-3xl font-black">No projects on the go</h1><p className="mx-auto mt-2 max-w-sm text-sm leading-relaxed text-muted-foreground">When you start a pattern, it’ll live here with your current row, materials and notes.</p><Link href="/library/upload" className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-primary px-5 py-3.5 font-heading text-sm font-extrabold text-white"><Plus className="size-4"/>Add a pattern</Link></div>}
